[rbx_binary] Write CFrame basic rotation ids
rojo-rbx/rbx-dom pull request #171
Opened 2021-04-11 18:30 UTC by kennethloeffler

Closes #129.

2021-04-11 19:09 UTC, kennethloeffler commented
> Creates a module and moves CFrame-related logic to
it. Renames special_case_to_rotation to to_basic_rotation_id
Its counterpart, from_basic_rotation_id, goes in the other
direction from rotation matrices to ids.

Whoops - these methods should be listed in the opposite order here.

2021-04-11 23:31 UTC, kennethloeffler commented
This does bring up the question of if we should do anything about non-orthonormal matrices, whether in the new `cframe` module or further up in `rbx_types`. Roblox Studio orthonormalizes CFrames' rotation matrices when setting them, so this doesn't seem like much of a problem to me - especially considering that one would really have to try in order to have a file that actually contains CFrames like this. Thus I wonder whether the above check is at all necessary. 

Without the comparison, in cases where they *do* differ, the end result would be one of the basic rotation matrices instead of the later orthonormalization by Studio. With respect only to this section of code: do we test for a bad matrix, and then pretend we never saw it (the current behavior)? or do we not test, and as a result inadvertently alter the contents of the file? I like the first option - we should probably make reasonable efforts to reflect the contents in as close to their original state as possible.

2021-04-12 21:15 UTC, LPGhatguy commented
I think we should leave non-orthonormalized matrices alone.

One goal of rbx-dom (that isn't really written down) is that we should be able to handle any _structurally_ valid model file, even if it's not _semantically_ valid. Roblox's DOM implementation, on the other hand, also does strict _semantic_ validation, which might include forcing CFrames to be orthonormalized when used on parts.

2021-04-12 21:38 UTC, Dekkonot commented
> I think we should leave non-orthonormalized matrices alone.

Agreed. If we start enforcing semantic correctness on files, it can get messy really quick. A DOM shouldn't decide what is or isn't correct as long as it can read it.

2021-04-13 21:54 UTC, kennethloeffler commented
Worth noting that it's now possible to give `from_basic_rotation_id` an invalid id and get back a garbage matrix.  Is this a problem?

2021-04-13 22:17 UTC, Dekkonot commented
I'm going to say no because the only way that will happen is if a codec like ours does it. Studio never produces garbage ID's like that.

2021-04-13 22:27 UTC, kennethloeffler commented on rbx_binary/src/deserializer.rs
> +                            let special_case = from_basic_rotation_id(id).ok_or_else(|| {
This will error for `id > 0x24`, but not for something like `id == 0x04` or `id == 0x24`. Maybe a little funky?

2021-04-13 22:44 UTC, kennethloeffler commented on rbx_binary/src/deserializer.rs
> +                            let special_case = from_basic_rotation_id(id).ok_or_else(|| {
I don't think I like this behavior, so we're going back to the match.

2021-04-13 23:15 UTC, kennethloeffler commented on rbx_binary/src/deserializer.rs
> +                            let special_case = from_basic_rotation_id(id).ok_or_else(|| {
On the other hand, we could guard against these - but that's probably less clear than simply enumerating all the valid ids in the match expression.

2021-04-14 01:13 UTC, LPGhatguy commented
How does Studio handle being given a garbage basic rotation ID? I'm worried that if more special cases are ever added, we'll silently corrupt them instead of knowingly fail.

If possible, we should reject invalid rotation IDs.

2021-04-14 01:46 UTC, kennethloeffler commented
We do currently reject them with an error: the deserializer emits an `InnerError::InvalidOrientationId` when `from_basic_rotation_id` fails to match. I think we should stick with a match for this function, because guarding against the invalid ids in the other implementation makes the code look way too voodoo for my taste.

I'm not sure what Roblox Studio does with them (yet) - I think I want to make a utility that lets me easily screw with property data blocks :P

2021-04-22 00:59 UTC, Dekkonot commented on rbx_types/src/basic_types.rs
> +    } else if abs_diff_eq!(value.abs(), 0.0) {
How does this differ from `abs_diff_eq!(value, 0.0)`?

2021-04-22 00:59 UTC, Dekkonot commented on rbx_types/src/basic_types.rs
> +fn get_normal_id(position: u8, value: i32) -> Option<u8> {
This feels rather cryptic - is there a chance we could get some documentation for it in-file?

2021-04-23 15:54 UTC, Dekkonot commented
@kennethloeffler I was more interested in getting an explanation of how it works rather than what it does. That's my fault, I wasn't very clear.

After giving it some thought though, I don't think that's necessary. It's pretty self-apparent *what* it's doing, and the how boils down to "this is how it works in Roblox".

2021-04-23 16:02 UTC, LPGhatguy requested changes

2021-04-23 17:10 UTC, LPGhatguy commented on rbx_types/src/basic_types.rs
> +        Some(one.copysign(value) as i32)
```suggestion
        Some(1.0f32.copysign(value) as i32)
```

or maybe

```suggestion
        Some(1 * value.signum() as i32)
```

When I made this suggestion, I don't think I realized that the return value was `i32`. Whichever of these makes the most sense to you should be good!

2021-04-23 17:34 UTC, LPGhatguy approved these changes

2021-04-23 17:34 UTC, merged