Verify scriptability of properties in generate_reflection
rojo-rbx/rbx-dom pull request #177
Opened 2021-05-07 01:34 UTC by kennethloeffler

This PR reintroduces the scriptability check from 5bca08f that we subsequently lost in 9866d06. Closes #153.

2021-05-07 20:04 UTC, kennethloeffler commented on generate_reflection/plugin/main.lua
> +		end
Thought of a possible issue here: if we can't read/write superclass properties on a particular subclass, but *can* on other subclasses, *and* we happen measure the former kind of subclass first, then these properties' measured scriptability will be wrong! AFAIK this is only possible with deprecated classes like `Speaker` that subclass `Instance` - we currently ignore these properties across the board, thus avoiding the issue. Should we worry about this?

2021-05-08 00:52 UTC, kennethloeffler commented
This seems like a more reliable approach to me. Are there perhaps any problems I'm not seeing with relying on the API dump for this information?

2021-05-08 19:17 UTC, LPGhatguy requested changes
This is a wonderful change. Minor comment on `if-let` vs `match` and then I think we're good to go.

2021-05-09 03:58 UTC, LPGhatguy approved these changes

2021-05-09 03:58 UTC, merged