Implement QDir in rbx_xml
rojo-rbx/rbx-dom pull request #182
Opened 2021-05-31 05:08 UTC by kennethloeffler

generate_reflection needs to be able to access Roblox Studio's auto-save path (see #181). It is stored in what is essentially a `.rbxmx` file in Roblox's installation root. Here's a piece of trivia for you: Roblox Studio will correctly read a path delimited with any number of (possibly interleaved) forward and back slashes, but always writes it back delimited with one forward slash.

2021-06-01 05:47 UTC, LPGhatguy requested changes
Easy implementation, question about future compatibility.

Can you also update the relevant CHANGELOG files?

2021-06-01 05:47 UTC, LPGhatguy commented on rbx_types/src/variant.rs
> +    QDir(std::path::PathBuf),
Should we newtype this? I'm a little afraid of the format eventually growing a not-weird-Qt-type path. We can sort of follow the lead from `Content` here.

2021-06-02 01:06 UTC, kennethloeffler commented
I just scattershot implemented various traits - let me know if you think we need more!

2021-06-02 01:35 UTC, LPGhatguy requested changes
Too many impls! I think we can cut down on these substantially because of how niche of a type this is.

2021-06-02 01:35 UTC, LPGhatguy commented on rbx_types/src/qdir.rs
> +}
Let's narrow these down to just `From<&Path>` and `From<PathBuf>`. Every impl we have here is another thing we have to uphold for forward compatibility and I think keeping a super niche type like this slim is probably okay.

2021-06-02 01:35 UTC, LPGhatguy commented on rbx_types/src/qdir.rs
> +}
I don't think a deref here is all that important. We can `AsRef` into `Path`, we're not making a total drop-in replacement.

2021-06-02 01:35 UTC, LPGhatguy commented on rbx_types/src/qdir.rs
> +}
I don't think we need this impl

2021-06-02 01:35 UTC, LPGhatguy commented on rbx_xml/src/types/qdir.rs
> +use rbx_dom_weak::types::QDir;
```suggestion
use rbx_dom_weak::types::QDir;

use crate::{
    core::XmlType,
    deserializer_core::XmlEventReader,
    error::{DecodeError, EncodeError},
    serializer_core::XmlEventWriter,
};
```

We usually order external crates above internal imports.

2021-06-05 23:02 UTC, kennethloeffler commented
Further work on #181 shows this to be unnecessary.

2021-06-05 23:02 UTC, closed without merging