Implement font attributes
rojo-rbx/rbx-dom pull request #299
Opened 2023-06-27 05:48 UTC by kennethloeffler

Closes #290.

Should the folder-with-font-attribute test files have more & varied font attributes added? I sort of want to add more, but I think the spec is correct, and I'm not sure how important it is to test against more values here

2023-06-27 06:09 UTC, Dekkonot commented
I don't imagine there's any variation in the way Fonts are serialized. One test is probably enough. I won't stop you from adding more, but I don't think it's necessary.

I'll give the code a once over in the morning but at a glance, please add this to the changelog 😉

2023-06-28 01:14 UTC, Dekkonot requested changes
No reason for us to bother with a `String` when we can just use `&'static str` but otherwise looks good to me.

2023-06-28 01:14 UTC, Dekkonot commented on rbx_types/src/attributes/error.rs
> +        field: String,
```suggestion
        field: &'static str,
```

2023-06-28 01:14 UTC, Dekkonot commented on rbx_types/src/attributes/reader.rs
> +                                field: "cached_face_id".to_string(),
```suggestion
                                field: "cached_face_id",
```

2023-06-28 01:14 UTC, Dekkonot commented on rbx_types/src/attributes/reader.rs
> +                        field: "family".to_string(),
```suggestion
                        field: "family",
```

2023-06-28 02:12 UTC, kennethloeffler commented
Commited from my iPhone

2023-06-28 02:19 UTC, Dekkonot approved these changes

2023-06-28 02:19 UTC, merged

2023-06-28 02:19 UTC, Dekkonot commented
Merged from my Android