Swap over to using `write_interleaved_bytes` and `read_interleaved_bytes` for binary format
rojo-rbx/rbx-dom pull request #330
Opened 2023-07-27 21:43 UTC by Dekkonot

This migrates the various `read_interleaved_XXX_array` and `write_interleaved_XXX_array` functions to use `read_interleaved_bytes` and `write_interleaved_bytes` respectively.

The end result is a lot simpler code and has no cost associated with it (I checked the assembly, both versions give us basically the same instructions). Benchmarking also supports this, as the compilation time on my machine is basically the same before and after once you account for noise.

Also I added documentation to all these functions and the integer transforming functions because I didn't like them sitting there undocumented.

2023-07-27 23:10 UTC, kennethloeffler commented
Massive nit:

The commit message is going to be 93 characters long (21 more characters than the recommended 72) when this gets merged... can you edit the title of this PR so it's more concise, maybe `Use generic interleaving methods in rbx_binary core`?

2023-07-28 20:24 UTC, Dekkonot commented
Just for you, yes, I can

2023-08-04 20:01 UTC, kennethloeffler requested changes

2023-08-04 20:07 UTC, kennethloeffler approved these changes

2023-08-04 20:09 UTC, merged