Use ScriptEditorService for updating Source
rojo-rbx/rbx-dom pull request #370
Opened 2023-10-11 15:37 UTC by Dekkonot

We need to start using `UpdateSourceAsync` and `GetEditorSource` for setting and getting `Script.Source` and `ModuleScript.Source`. So, this does that, using `task.spawn` to make sure it isn't blocking as we discussed elsewhere.

This is not a permanent solution. Long-term, we should try to properly support property sets and gets being async, or properly commit to consumers like Rojo having to handle it. For now though, this should be fine.

Also I fixed a lint because it was bothering me. Let me know if I should revert that and fix it in a different PR lol

2023-10-11 16:20 UTC, nezuo commented
Doesn't this need to also support `LocalScript`?

2023-10-11 16:27 UTC, Dekkonot commented
[LocalScript inherits from Script](https://github.com/MaximumADHD/Roblox-Client-Tracker/blob/roblox/API-Dump.txt#L2876), so it already does. It's a surprising inheritance but very helpful.

2023-10-11 16:34 UTC, nezuo requested changes

2023-10-11 16:34 UTC, nezuo commented on rbx_dom_lua/src/customProperties.lua
> +
There aren't newlines between the previous entries.

2023-10-12 21:49 UTC, nezuo approved these changes

2023-10-13 15:28 UTC, merged