Make pretty JSON optional for `generate` subcommand
rojo-rbx/rbx-dom pull request #401
Opened 2024-03-06 18:26 UTC by DervexHero

This PR makes writing of database from `generate` subcommand in pretty-printed JSON optional by adding `--pretty` option. I think that it makes sense as these files are not intended to be read by humans and it reduces the file size from `1.6MB` to `796KB`.

2024-03-06 19:08 UTC, kennethloeffler requested changes
I'm fine with this option, and it may be useful once we start publishing databases to GitHub releases. 

I slightly disagree with "not intended to be read by humans." We do want to diff and read the database with our eyes quite frequently (whenever we open PRs to update it), and some editors don't perform well on extremely long lines! I'd prefer renaming this option to something like `no-pretty` and swapping the conditional, so that the default result is pretty printed, and the behavior of our existing `gen-reflection` script remains the same.

2024-03-06 19:08 UTC, kennethloeffler commented on rbx_reflector/src/cli/generate.rs
> +    pub pretty: bool,
```suggestion
    /// Whether to pretty-print the JSON output. This has no effect on MessagePack.
    #[clap(long)]
    pub no_pretty: bool,
```

2024-03-06 19:08 UTC, kennethloeffler commented on rbx_reflector/src/cli/generate.rs
> +                    result.context("Could not serialize reflection database as JSON")?;
```suggestion
                    let result = if self.no_pretty {
                        serde_json::to_writer(&mut file, &database)
                    } else {
                        serde_json::to_writer_pretty(&mut file, &database)
                    };

                    result.context("Could not serialize reflection database as JSON")?;
```

2024-03-06 19:48 UTC, DervexHero commented
> it may be useful once we start publishing databases to GitHub releases

I think that it is already pretty useful e.g. when including `rbx_dom_lua` in other projects.

> I slightly disagree with "not intended to be read by humans." We do want to diff and read the database with our eyes quite frequently (whenever we open PRs to update it)

Oh I thought that e.g. `rbx_dom_lua` uses 100% auto generated database from `rbx_reflector`, makes sense then.

> some editors don't perform well on extremely long lines

That's good to now!

2024-03-06 20:49 UTC, kennethloeffler commented
> Oh I thought that e.g. rbx_dom_lua uses 100% auto generated database from rbx_reflector, makes sense then.

We do use rbx_reflector to generate the database in rbx_dom_lua  -  I'd just like to be able to easily see how the database has changed after an update. Pretty printed JSON diffs pretty well, but it's much harder to see what changed when it's all slammed into a single line. It's certainly possible to prettify it manually after the fact... but I'd rather not add another step 😄

2024-03-07 02:12 UTC, kennethloeffler approved these changes

2024-03-07 16:58 UTC, merged